"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import PayslipTemplate, { type PayslipData } from "@/components/PayslipTemplate";
import { supabase } from "@/app/lib/supabaseClient";

type Slip = { id:string; employee_id:string; business_id:string; basic_pay:number|null; bonus:number|null; overtime_pay:number|null; gross_pay:number|null; taxable_income:number|null; uif_employee:number|null; paye:number|null; other_deductions:number|null; payment_method:string|null; payroll_month:string|null; payment_date:string|null; pay_period_month:number|null; pay_period_year:number|null };
type Employee = { id:string; full_name:string|null; first_name:string|null; last_name:string|null; employee_number:string|null; position:string|null; department:string|null; id_number:string|null; payment_method:string|null; bank_name:string|null; account_number:string|null; leave_balance:number|null };
type Business = { business_name:string|null; trading_name:string|null; registration_number:string|null; paye_reference:string|null; uif_reference:string|null; address:string|null; phone:string|null; email:string|null; logo_url:string|null; paye_enabled:boolean|null; uif_enabled:boolean|null; show_leave_balances:boolean|null };

export default function BulkPayslipPrintPage() {
  const params = useSearchParams(); const month = params.get("month") || ""; const [slips, setSlips] = useState<Slip[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [business, setBusiness] = useState<Business | null>(null); const [message, setMessage] = useState("Loading payslips...");
  useEffect(() => { void load(); }, [month]);
  async function load() { const { data:{user} }=await supabase.auth.getUser(); if(!user) return setMessage("Sign in to print payslips."); const {data:profile}=await supabase.from("profiles").select("business_id").eq("id",user.id).maybeSingle(); if(!profile?.business_id) return setMessage("Business profile not found."); let query=supabase.from("payslips").select("*").eq("business_id",profile.business_id).order("employee_id"); if(month) query=query.eq("payroll_month",month); const {data:slipData,error}=await query; if(error) return setMessage(error.message); if(!(slipData||[]).length) return setMessage("No payslips found for this payroll period."); const ids=(slipData||[]).map((item)=>item.employee_id); const [employeeResult,businessResult]=await Promise.all([supabase.from("employees").select("*").in("id",ids),supabase.from("businesses").select("*").eq("id",profile.business_id).maybeSingle()]); setSlips((slipData||[]) as Slip[]);setEmployees((employeeResult.data||[]) as Employee[]);setBusiness(businessResult.data as Business|null);setMessage(""); }
  const templates=useMemo(() => slips.map((slip) => toTemplate(slip, employees.find((employee)=>employee.id===slip.employee_id), business, slips)), [slips,employees,business]);
  return <main style={page}><header style={header}><div><p style={eyebrow}>Paper payroll</p><h1 style={title}>Bulk payslip print</h1><p style={subtitle}>{month ? `Payroll period: ${month}` : "All available payslips"} · {templates.length} payslip(s)</p></div><div style={actions}><Link href="/employer/payslips" style={back}>← Back to payslips</Link><button style={button} disabled={!templates.length} onClick={() => window.print()}>Print / Save PDF</button></div></header>{message ? <div style={notice}>{message}</div> : <section>{templates.map((payslip,index)=><div key={slips[index].id} style={slipPage}><PayslipTemplate payslip={payslip}/></div>)}</section>}</main>;
}
function toTemplate(slip:Slip, employee:Employee|undefined, business:Business|null, all:Slip[]):PayslipData { const ytd=all.filter((item)=>item.employee_id===slip.employee_id&&item.pay_period_year===slip.pay_period_year&&Number(item.pay_period_month||0)<=Number(slip.pay_period_month||12)); const mask=(value?:string|null)=>!value?"-":value.length<=4?value:`******${value.slice(-4)}`; const period=slip.payroll_month?new Date(`${slip.payroll_month}-01T00:00:00`).toLocaleDateString("en-ZA",{month:"long",year:"numeric"}):"Payroll period"; const payDate=slip.payment_date?new Date(slip.payment_date).toLocaleDateString("en-ZA"):"-"; const showPaye=business?.paye_enabled??true,showUif=business?.uif_enabled??true; return {company:{name:business?.trading_name||business?.business_name||"WageFlow Business",logoUrl:business?.logo_url||"/wageflow-logo.png",address:business?.address||"-",registrationNumber:business?.registration_number||"-",payeReference:business?.paye_reference||"-",uifReference:business?.uif_reference||"-",phone:business?.phone||"-",email:business?.email||"-"},employee:{name:employee?.full_name||`${employee?.first_name||""} ${employee?.last_name||""}`.trim()||"Employee",employeeNumber:employee?.employee_number||"-",position:employee?.position||"-",department:employee?.department||"-",idNumber:employee?.id_number||"-",paymentMethod:slip.payment_method||employee?.payment_method||"-",bankName:employee?.bank_name||"-",accountNumber:mask(employee?.account_number)},pay:{period,payDate,payReference:`PAY-${slip.payroll_month||"MONTH"}-${employee?.employee_number||slip.id.slice(0,6)}`},earnings:[{item:"Basic Salary",amount:Number(slip.basic_pay||0)},{item:"Overtime",amount:Number(slip.overtime_pay||0)},{item:"Bonus",amount:Number(slip.bonus||0)}].filter((item)=>item.amount>0),deductions:[showPaye?{item:"PAYE",amount:Number(slip.paye||0)}:null,showUif?{item:"UIF",amount:Number(slip.uif_employee||0)}:null,{item:"Other Deductions",amount:Number(slip.other_deductions||0)}].filter((item):item is {item:string;amount:number}=>Boolean(item)&&item.amount>0),ytd:{from:`01 March ${slip.pay_period_year||new Date().getFullYear()}`,to:payDate,gross:ytd.reduce((sum,item)=>sum+Number(item.gross_pay||0),0),taxable:ytd.reduce((sum,item)=>sum+Number(item.taxable_income||item.gross_pay||0),0),paye:ytd.reduce((sum,item)=>sum+Number(item.paye||0),0),uif:ytd.reduce((sum,item)=>sum+Number(item.uif_employee||0),0)},leave:{annual:Number(employee?.leave_balance||0)},settings:{showPaye,showUif,showLeave:business?.show_leave_balances??true}}; }
const page={minHeight:"100vh",padding:"28px",background:"#f4fbfb",fontFamily:"Arial, sans-serif"};const header={maxWidth:1050,margin:"0 auto 18px",display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start"};const eyebrow={margin:0,color:"#0f766e",fontSize:12,fontWeight:800,textTransform:"uppercase" as const};const title={margin:"6px 0",color:"#0f172a"};const subtitle={margin:0,color:"#64748b"};const actions={display:"flex",gap:10,alignItems:"center"};const back={color:"#0f766e",fontWeight:800,textDecoration:"none"};const button={background:"#0f766e",color:"#fff",border:0,borderRadius:10,padding:"10px 14px",fontWeight:800,cursor:"pointer"};const notice={maxWidth:1050,margin:"0 auto",padding:20,background:"#fff",borderRadius:16,color:"#155e75"};const slipPage={breakAfter:"page" as const,pageBreakAfter:"always" as const,marginBottom:24};
