"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/app/lib/supabaseClient";

type Admin = { id: string; email: string; full_name: string | null; access_status: string; admin_permissions: string[]; created_at: string };
const labels: Record<string, string> = { employees: "Employees", payroll: "Payroll preparation", payslips: "Payslips", hr: "HR records and approvals", reports: "Reports", settings: "Business settings" };

export default function EmployerAdminsPage() {
  const [admins, setAdmins] = useState<Admin[]>([]); const [permissions, setPermissions] = useState<string[]>([]); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [grants, setGrants] = useState<string[]>([]); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const request = useCallback(async (method = "GET", body?: object, id?: string) => { const { data: { session } } = await supabase.auth.getSession(); if (!session) return { error: "Your session has expired." }; const response = await fetch(`/api/employer/admins${id ? `?id=${encodeURIComponent(id)}` : ""}`, { method, headers: { Authorization: `Bearer ${session.access_token}`, ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined }); const result = await response.json().catch(() => ({})); return response.ok ? result : { error: result.error || "Request failed." }; }, []);
  const load = useCallback(async () => { const result = await request(); if (result.error) setMessage(result.error); else { setAdmins(result.admins || []); setPermissions(result.permissions || []); } }, [request]);
  useEffect(() => { void load(); }, [load]);
  function toggle(permission: string) { setGrants((current) => current.includes(permission) ? current.filter((item) => item !== permission) : [...current, permission]); }
  async function invite() { setSaving(true); setMessage(""); const result = await request("POST", { name, email, permissions: grants }); if (result.error) setMessage(result.error); else { setMessage(result.message); setName(""); setEmail(""); setGrants([]); await load(); } setSaving(false); }
  async function save(admin: Admin) { setSaving(true); const result = await request("PATCH", { id: admin.id, permissions: admin.admin_permissions }); setMessage(result.error || "Permissions updated."); if (!result.error) await load(); setSaving(false); }
  async function deactivate(id: string) { if (!window.confirm("Remove this administrator's access? They will no longer be able to sign in to this business.")) return; setSaving(true); const result = await request("DELETE", undefined, id); setMessage(result.error || "Administrator access removed."); if (!result.error) await load(); setSaving(false); }
  function toggleAdmin(id: string, permission: string) { setAdmins((current) => current.map((admin) => admin.id !== id ? admin : { ...admin, admin_permissions: admin.admin_permissions.includes(permission) ? admin.admin_permissions.filter((item) => item !== permission) : [...admin.admin_permissions, permission] })); }
  return <main style={page}><section style={header}><div><p style={eyebrow}>Business owner controls</p><h1 style={title}>Employer Admins</h1><p style={subtitle}>Invite trusted colleagues and choose exactly which workspaces they can use. Billing, bank and tax details, final payroll approval, and admin management stay with the business owner.</p></div><Link href="/employer" style={back}>Back to dashboard</Link></section>{message && <div style={notice}>{message}</div>}<section style={card}><h2 style={heading}>Invite an administrator</h2><div style={formGrid}><input style={input} value={name} onChange={(event) => setName(event.target.value)} placeholder="Full name" /><input style={input} value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email address" /></div><PermissionPicker permissions={permissions} selected={grants} onToggle={toggle} /><button style={button} disabled={saving} onClick={invite}>{saving ? "Saving…" : "Invite administrator"}</button></section><section style={card}><h2 style={heading}>Current administrators</h2>{admins.length === 0 ? <p style={muted}>No employer administrators have been invited yet.</p> : admins.map((admin) => <article key={admin.id} style={adminCard}><div><strong>{admin.full_name || "Unnamed administrator"}</strong><p style={muted}>{admin.email} · {admin.access_status}</p></div><PermissionPicker permissions={permissions} selected={admin.admin_permissions || []} onToggle={(permission) => toggleAdmin(admin.id, permission)} /><div style={actions}><button style={outline} disabled={saving} onClick={() => save(admin)}>Save permissions</button><button style={danger} disabled={saving} onClick={() => deactivate(admin.id)}>Remove access</button></div></article>)}</section></main>;
}

function PermissionPicker({ permissions, selected, onToggle }: { permissions: string[]; selected: string[]; onToggle: (permission: string) => void }) { return <div style={permissionsStyle}>{permissions.map((permission) => <label key={permission} style={permissionLabel}><input type="checkbox" checked={selected.includes(permission)} onChange={() => onToggle(permission)} /> {labels[permission] || permission}</label>)}</div>; }
const page={minHeight:"100vh",padding:38,fontFamily:"Arial, sans-serif",background:"#f4f8fb",color:"#0f172a"}; const header={display:"flex",justifyContent:"space-between",gap:18,flexWrap:"wrap" as const,marginBottom:26}; const eyebrow={margin:"0 0 7px",color:"#0f766e",fontWeight:900,fontSize:12,textTransform:"uppercase" as const}; const title={margin:"0 0 10px",fontSize:34,color:"#0f766e"}; const subtitle={margin:0,maxWidth:780,color:"#64748b",lineHeight:1.6}; const back={alignSelf:"start",padding:"10px 14px",border:"1px solid #0f766e",borderRadius:10,color:"#0f766e",textDecoration:"none",fontWeight:800}; const card={background:"#fff",border:"1px solid #e2e8f0",borderRadius:18,padding:24,marginBottom:20,boxShadow:"0 8px 24px rgba(15,23,42,.04)"}; const heading={margin:"0 0 16px",fontSize:21}; const formGrid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}; const input={width:"100%",boxSizing:"border-box" as const,padding:12,border:"1px solid #cbd5e1",borderRadius:10,fontSize:15}; const permissionsStyle={display:"flex",flexWrap:"wrap" as const,gap:10,margin:"17px 0"}; const permissionLabel={padding:"9px 11px",background:"#f8fafc",border:"1px solid #dbe4ea",borderRadius:9,fontSize:13,fontWeight:700}; const button={padding:"11px 16px",border:0,borderRadius:10,background:"#0f766e",color:"#fff",fontWeight:800,cursor:"pointer"}; const notice={marginBottom:18,padding:13,borderRadius:10,background:"#ecfeff",border:"1px solid #a5f3fc",color:"#155e75",fontWeight:700}; const muted={color:"#64748b",margin:"5px 0",fontSize:14}; const adminCard={padding:"18px 0",borderTop:"1px solid #e2e8f0"}; const actions={display:"flex",gap:10,flexWrap:"wrap" as const}; const outline={padding:"9px 12px",border:"1px solid #0f766e",borderRadius:9,background:"#fff",color:"#0f766e",fontWeight:800,cursor:"pointer"}; const danger={padding:"9px 12px",border:"1px solid #dc2626",borderRadius:9,background:"#fff",color:"#b91c1c",fontWeight:800,cursor:"pointer"};
