"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/app/lib/supabaseClient";

type ChangeRequest = { id: string; request_type: string; requested_changes: Record<string, string>; status: string; employee_note: string | null; employer_note: string | null; evidence_path: string | null; created_at: string; employees?: { first_name?: string | null; last_name?: string | null; employee_number?: string | null } | null };
const labels: Record<string, string> = { contact: "Contact details", emergency_contact: "Emergency contact", banking: "Banking details" };

export default function EmployerChangeRequestsPage() {
  const [requests, setRequests] = useState<ChangeRequest[]>([]); const [notes, setNotes] = useState<Record<string, string>>({}); const [message, setMessage] = useState(""); const [saving, setSaving] = useState("");
  async function headers() { const { data: { session } } = await supabase.auth.getSession(); return session ? { Authorization: `Bearer ${session.access_token}` } : null; }
  async function load() { const auth = await headers(); if (!auth) return setMessage("Your session has expired. Please sign in again."); const response = await fetch("/api/profile-change-requests", { headers: auth }); const result = await response.json().catch(() => ({})); if (!response.ok) setMessage(result.error || "Requests could not be loaded."); else setRequests(result.requests || []); }
  useEffect(() => { void load(); }, []);
  async function decide(id: string, status: "Approved" | "Declined") { const auth = await headers(); if (!auth) return setMessage("Your session has expired. Please sign in again."); setSaving(id); const response = await fetch("/api/profile-change-requests/decision", { method: "POST", headers: { ...auth, "Content-Type": "application/json" }, body: JSON.stringify({ requestId: id, status, employerNote: notes[id] || "" }) }); const result = await response.json().catch(() => ({})); if (!response.ok) setMessage(result.error || "Decision could not be saved."); else { setMessage(`Request ${status.toLowerCase()}.`); await load(); } setSaving(""); }
  async function openEvidence(id: string) { const auth = await headers(); if (!auth) return setMessage("Your session has expired. Please sign in again."); const response = await fetch(`/api/profile-change-requests/evidence?id=${encodeURIComponent(id)}`, { headers: auth }); const result = await response.json().catch(() => ({})); if (!response.ok) setMessage(result.error || "Document could not be opened."); else window.open(result.url, "_blank", "noopener,noreferrer"); }
  return <main style={page}><section style={header}><div><p style={eyebrow}>Employer approval</p><h1 style={title}>Employee Change Requests</h1><p style={subtitle}>Review requested profile changes. Approval applies the permitted fields to the employee record; banking changes include private bank-confirmation evidence.</p></div><Link href="/employer" style={back}>Back to Dashboard</Link></section>{message && <p style={notice}>{message}</p>}<section style={card}><div style={top}><h2 style={heading}>Requests</h2><button style={outline} onClick={load}>Refresh</button></div>{requests.length === 0 ? <p style={muted}>No employee profile-change requests yet.</p> : <div style={list}>{requests.map((request) => { const employee = request.employees; const name = `${employee?.first_name || ""} ${employee?.last_name || ""}`.trim() || "Employee"; return <article key={request.id} style={requestCard}><div style={top}><div><strong>{name}</strong><p style={muted}>{employee?.employee_number || "No employee number"} · {labels[request.request_type] || request.request_type} · {new Date(request.created_at).toLocaleDateString("en-ZA")}</p></div><span style={badge(request.status)}>{request.status}</span></div><p style={changesText}>{Object.entries(request.requested_changes || {}).filter(([, value]) => value).map(([key, value]) => `${key.replaceAll("_", " ")}: ${value}`).join(" · ")}</p>{request.employee_note && <p style={muted}>Employee note: {request.employee_note}</p>}{request.evidence_path && <button style={outline} onClick={() => openEvidence(request.id)}>View bank confirmation</button>}{request.status === "Pending" && <><textarea style={textarea} value={notes[request.id] || ""} onChange={(event) => setNotes((current) => ({ ...current, [request.id]: event.target.value }))} placeholder="Note to employee (required if declining)" /><div style={actions}><button style={button} disabled={saving === request.id} onClick={() => decide(request.id, "Approved")}>Approve & apply changes</button><button style={danger} disabled={saving === request.id} onClick={() => decide(request.id, "Declined")}>Decline</button></div></>}{request.employer_note && <p style={muted}>Employer note: {request.employer_note}</p>}</article>; })}</div>}</section></main>;
}
const page={minHeight:"100vh",padding:38,background:"#f4f8fb",color:"#0f172a"}; const header={display:"flex",justifyContent:"space-between",gap:18,flexWrap:"wrap" as const,marginBottom:24}; const eyebrow={margin:"0 0 7px",color:"#b45309",fontWeight:900,fontSize:12,textTransform:"uppercase" as const}; const title={margin:0,color:"#0f766e",fontSize:34}; const subtitle={maxWidth:760,color:"#64748b",lineHeight:1.6}; const back={alignSelf:"start",padding:"10px 14px",border:"1px solid #0f766e",borderRadius:10,color:"#0f766e",textDecoration:"none",fontWeight:800}; const card={maxWidth:1080,padding:22,border:"1px solid #e2e8f0",borderRadius:18,background:"#fff"}; const top={display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",flexWrap:"wrap" as const}; const heading={margin:0,fontSize:20}; const muted={margin:"5px 0",color:"#64748b",fontSize:13}; const notice={maxWidth:1080,padding:13,border:"1px solid #a5f3fc",borderRadius:10,background:"#ecfeff",color:"#155e75",fontWeight:700}; const list={display:"grid",gap:12,marginTop:16}; const requestCard={padding:17,border:"1px solid #e2e8f0",borderRadius:13,background:"#f8fafc"}; const changesText={fontSize:14,color:"#334155"}; const textarea={width:"100%",boxSizing:"border-box" as const,minHeight:74,padding:10,border:"1px solid #cbd5e1",borderRadius:9,margin:"10px 0"}; const actions={display:"flex",gap:10,flexWrap:"wrap" as const}; const button={padding:"10px 13px",border:0,borderRadius:9,background:"#0f766e",color:"#fff",fontWeight:800,cursor:"pointer"}; const outline={padding:"9px 12px",border:"1px solid #0f766e",borderRadius:9,background:"#fff",color:"#0f766e",fontWeight:800,cursor:"pointer"}; const danger={padding:"10px 13px",border:"1px solid #dc2626",borderRadius:9,background:"#fff",color:"#b91c1c",fontWeight:800,cursor:"pointer"}; const badge=(status:string)=>({padding:"4px 8px",borderRadius:999,background:status==="Approved"?"#dcfce7":status==="Declined"?"#fee2e2":"#fef3c7",color:status==="Approved"?"#166534":status==="Declined"?"#991b1b":"#92400e",fontWeight:800,fontSize:12});
