"use client";

import Link from "next/link";
import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import { supabase } from "../../../lib/supabaseClient";

type Employee = { id: string; full_name?: string | null; first_name?: string | null; last_name?: string | null; employment_status?: string | null; status?: string | null };
type Policy = { id: string; title: string; version: string; policy_text?: string | null; file_path?: string | null; published_at: string; policy_assignments?: { id: string; employee_id: string; policy_acknowledgements?: { id: string; acknowledged_at: string }[] }[] };

export default function EmployerPoliciesPage() {
  const [policies, setPolicies] = useState<Policy[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [selected, setSelected] = useState<string[]>([]); const [title, setTitle] = useState(""); const [version, setVersion] = useState("1.0"); const [policyText, setPolicyText] = useState(""); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void load(); }, []);
  const activeEmployees = useMemo(() => employees.filter((employee) => !["terminated", "inactive"].includes(String(employee.status || employee.employment_status || "active").toLowerCase())), [employees]);
  async function request(url: string, init?: RequestInit) { const { data: { session } } = await supabase.auth.getSession(); const response = await fetch(url, { ...init, headers: { ...(init?.headers || {}), Authorization: `Bearer ${session?.access_token || ""}` } }); return { response, body: await response.json().catch(() => ({})) }; }
  async function load() { const { response, body } = await request("/api/policies"); if (!response.ok) setMessage(body.error || "Policies could not be loaded."); else { setPolicies(body.policies || []); setEmployees(body.employees || []); } }
  function toggle(id: string) { setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]); }
  async function publish(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const form = new FormData(); form.set("title", title); form.set("version", version); form.set("policyText", policyText); form.set("employeeIds", JSON.stringify(selected)); if (file) form.set("file", file); const { response, body } = await request("/api/policies", { method: "POST", body: form }); setSaving(false); if (!response.ok) return setMessage(body.error || "Policy could not be published."); setTitle(""); setVersion("1.0"); setPolicyText(""); setFile(null); setSelected([]); setMessage("Policy published and assigned employees have been notified."); await load(); }
  return <main style={page}><header style={header}><div><p style={eyebrow}>Employee communication</p><h1 style={titleStyle}>Policies & acknowledgements</h1><p style={subtitle}>Publish a policy to selected employees and retain a dated acknowledgement record.</p></div><Link href="/employer/hr" style={back}>← Back to HR Records</Link></header>{message && <p style={notice}>{message}</p>}<section style={card}><h2 style={heading}>Publish policy</h2><form onSubmit={publish}><div style={grid}><Field label="Policy title"><input required style={input} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Example: Leave policy" /></Field><Field label="Version"><input required style={input} value={version} onChange={(event) => setVersion(event.target.value)} /></Field></div><Field label="Policy text"><textarea style={{ ...input, minHeight: 130 }} value={policyText} onChange={(event) => setPolicyText(event.target.value)} placeholder="Paste the policy text here, or upload the approved policy document below." /></Field><Field label="Policy document (optional)"><input style={input} type="file" accept=".pdf,.docx,.jpg,.jpeg,.png" onChange={(event) => setFile(event.target.files?.[0] || null)} /></Field><div style={assignmentHeader}><strong>Assign to employees</strong><button type="button" style={textButton} onClick={() => setSelected(selected.length === activeEmployees.length ? [] : activeEmployees.map((employee) => employee.id))}>{selected.length === activeEmployees.length ? "Clear all" : "Select all active"}</button></div><div style={employeeGrid}>{activeEmployees.map((employee) => <label key={employee.id} style={check}><input type="checkbox" checked={selected.includes(employee.id)} onChange={() => toggle(employee.id)} /> {employeeName(employee)}</label>)}</div><button disabled={saving} style={button}>{saving ? "Publishing…" : "Publish and request acknowledgement"}</button></form></section><section style={card}><h2 style={heading}>Published policies</h2>{policies.length === 0 ? <p style={muted}>No policies have been published yet.</p> : <div style={list}>{policies.map((policy) => { const assignments = policy.policy_assignments || []; const acknowledged = assignments.filter((assignment) => assignment.policy_acknowledgements?.length).length; return <article key={policy.id} style={policyCard}><div><strong>{policy.title}</strong><p style={muted}>Version {policy.version} · Published {new Date(policy.published_at).toLocaleDateString("en-ZA")}</p>{policy.file_path && <a href={`/api/policies/${policy.id}/document`} target="_blank" style={link}>Open policy document</a>}</div><div style={progress}><strong>{acknowledged} / {assignments.length}</strong><span style={muted}> acknowledged</span></div></article>; })}</div>}</section></main>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label style={field}><span style={labelStyle}>{label}</span>{children}</label>; }
function employeeName(employee: Employee) { return employee.full_name || `${employee.first_name || ""} ${employee.last_name || ""}`.trim() || "Employee"; }
const page = { minHeight: "100vh", padding: "28px clamp(16px,3vw,42px)", background: "#f4f8fb", color: "#0f172a" }; const header = { display: "flex", justifyContent: "space-between", gap: 16, flexWrap: "wrap" as const, marginBottom: 22 }; const eyebrow = { margin: 0, color: "#b7791f", fontSize: 12, fontWeight: 800, textTransform: "uppercase" as const }; const titleStyle = { margin: "5px 0", fontSize: "clamp(26px,3vw,30px)", color: "#0f766e" }; const subtitle = { margin: 0, color: "#64748b", maxWidth: 650, lineHeight: 1.55 }; const back = { alignSelf: "flex-start", padding: "10px 15px", border: "1px solid #0f766e", borderRadius: 10, color: "#0f766e", fontWeight: 800, textDecoration: "none" }; const card = { background: "#fff", border: "1px solid #e2e8f0", borderRadius: 16, padding: 20, marginBottom: 18, boxShadow: "0 8px 24px rgba(15,23,42,.05)" }; const heading = { margin: "0 0 16px", fontSize: 19 }; const grid = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 14 }; const field = { display: "block", marginBottom: 14 }; const labelStyle = { display: "block", fontWeight: 800, fontSize: 13, color: "#475569", marginBottom: 6 }; const input = { boxSizing: "border-box" as const, width: "100%", padding: 11, border: "1px solid #cbd5e1", borderRadius: 10, font: "inherit", background: "#fff" }; const assignmentHeader = { display: "flex", justifyContent: "space-between", gap: 12, margin: "14px 0 8px" }; const employeeGrid = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(210px,1fr))", gap: 8, marginBottom: 18 }; const check = { padding: 10, border: "1px solid #e2e8f0", borderRadius: 9, fontSize: 14 }; const button = { padding: "11px 16px", background: "#0f766e", color: "#fff", border: 0, borderRadius: 10, fontWeight: 800, cursor: "pointer" }; const textButton = { border: 0, background: "transparent", color: "#0f766e", fontWeight: 800, cursor: "pointer" }; const notice = { background: "#ecfeff", color: "#155e75", padding: 12, borderRadius: 10, fontWeight: 700 }; const muted = { color: "#64748b", margin: "5px 0", lineHeight: 1.5 }; const list = { display: "grid", gap: 10 }; const policyCard = { display: "flex", justifyContent: "space-between", gap: 16, alignItems: "center", border: "1px solid #e2e8f0", padding: 14, borderRadius: 12, flexWrap: "wrap" as const }; const progress = { color: "#0f766e" }; const link = { color: "#0f766e", fontWeight: 700 };
