"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/app/lib/supabaseClient";
import { Pagination } from "@/components/Pagination";

type Admin = { id: string; email: string; full_name: string | null; role: string; access_status: string; created_at: string };

export default function MasterAdminsPage() {
  const [admins, setAdmins] = useState<Admin[]>([]); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [currentPage, setCurrentPage] = useState(1);
  const request = useCallback(async (body?: object) => { const { data: { session } } = await supabase.auth.getSession(); if (!session) return { error: "Your session has expired." }; const response = await fetch("/api/master/admins", { method: body ? "POST" : "GET", headers: { Authorization: `Bearer ${session.access_token}`, ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined }); const data = await response.json().catch(() => ({})); return response.ok ? data : { error: data.error || "Request failed." }; }, []);
  const load = useCallback(async () => { const result = await request(); if (result.error) setMessage(result.error); else setAdmins(result.admins || []); }, [request]);
  useEffect(() => { void load(); }, [load]);
  async function invite() { setSaving(true); setMessage(""); const result = await request({ name, email }); setMessage(result.error || result.message); if (!result.error) { setName(""); setEmail(""); await load(); } setSaving(false); }
  const pageSize = 10; const totalPages = Math.max(1, Math.ceil(admins.length / pageSize)); const safePage = Math.min(currentPage, totalPages); const visibleAdmins = admins.slice((safePage - 1) * pageSize, safePage * pageSize);
  return <main style={page}><section style={header}><div><p style={eyebrow}>Platform security</p><h1 style={title}>Master Admins</h1><p style={subtitle}>Invite trusted platform administrators. Master Admins can access the Master Portal, while no client payroll records are exposed by default.</p></div><Link href="/master" style={back}>← Back to Master Dashboard</Link></section>{message && <div style={notice}>{message}</div>}<section style={card}><h2 style={heading}>Invite Master Admin</h2><div style={form}><input style={input} value={name} onChange={(event) => setName(event.target.value)} placeholder="Full name" /><input style={input} value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email address" /><button style={button} disabled={saving} onClick={invite}>{saving ? "Sending…" : "Invite Master Admin"}</button></div></section><section style={card}><h2 style={heading}>Current Master access</h2>{admins.length === 0 ? <p style={muted}>No Master Admin accounts found.</p> : <><div style={tableWrap}><table style={table}><thead><tr><th style={th}>Admin</th><th style={th}>Role</th><th style={th}>Status</th><th style={th}>Created</th></tr></thead><tbody>{visibleAdmins.map((admin) => <tr key={admin.id}><td style={td}><strong>{admin.full_name || "Unnamed administrator"}</strong><br /><span style={muted}>{admin.email}</span></td><td style={td}>{admin.role}</td><td style={td}>{admin.access_status}</td><td style={td}>{admin.created_at ? new Date(admin.created_at).toLocaleDateString() : "—"}</td></tr>)}</tbody></table></div><Pagination page={safePage} totalPages={totalPages} onPageChange={setCurrentPage} totalItems={admins.length} pageSize={pageSize} /></>}</section></main>;
}
const page={minHeight:"100vh",padding:38,fontFamily:"Arial, sans-serif",background:"#f4f8fb",color:"#0f172a"}; const header={display:"flex",justifyContent:"space-between",gap:18,flexWrap:"wrap" as const,marginBottom:26}; const eyebrow={margin:"0 0 7px",color:"#b45309",fontWeight:900,fontSize:12,textTransform:"uppercase" as const}; const title={margin:"0 0 10px",fontSize:34,color:"#0b6158"}; const subtitle={margin:0,maxWidth:760,color:"#64748b",lineHeight:1.6}; const back={alignSelf:"start",padding:"10px 14px",border:"1px solid #0f766e",borderRadius:10,color:"#0f766e",textDecoration:"none",fontWeight:800}; const card={background:"#fff",border:"1px solid #e2e8f0",borderRadius:18,padding:24,marginBottom:20,boxShadow:"0 8px 24px rgba(15,23,42,.04)"}; const heading={margin:"0 0 16px",fontSize:21}; const form={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12}; const input={width:"100%",boxSizing:"border-box" as const,padding:12,border:"1px solid #cbd5e1",borderRadius:10,fontSize:15}; const button={padding:"11px 16px",border:0,borderRadius:10,background:"#0f766e",color:"#fff",fontWeight:800,cursor:"pointer"}; const notice={marginBottom:18,padding:13,borderRadius:10,background:"#ecfeff",border:"1px solid #a5f3fc",color:"#155e75",fontWeight:700}; const muted={color:"#64748b",fontSize:13}; const tableWrap={overflowX:"auto" as const}; const table={width:"100%",borderCollapse:"collapse" as const,minWidth:650}; const th={textAlign:"left" as const,padding:12,borderBottom:"1px solid #e2e8f0",color:"#475569",fontSize:12,textTransform:"uppercase" as const}; const td={padding:12,borderBottom:"1px solid #e2e8f0",fontSize:14};
