"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { supabase } from "@/app/lib/supabaseClient";
import { Pagination } from "@/components/Pagination";

type Subscription = { id:string; business_id:string|null; plan_name:string|null; monthly_fee:number|null; setup_fee:number|null; setup_paid:boolean|null; subscription_status:string|null; created_at?:string|null };
type Business = { id:string; business_name:string; status:string|null };
type Statement = { id:string; subscription_id:string; statement_type:"setup"|"monthly"; statement_month:string; amount:number; status:string; recipient_email:string|null; paid_at:string|null; emailed_at:string|null; payment_reference:string|null; created_at:string };
type BillingRow = Subscription & { businessName:string; businessStatus:string|null };
const PAGE_SIZE=10;
const plans=["Starter","Pilot","Growth","Daily Bloom","Edu Bloom","Demo"] as const;
const planFees:Record<(typeof plans)[number],number>={Starter:199,Pilot:0,Growth:299,"Daily Bloom":0,"Edu Bloom":0,Demo:0};
const statuses=["active","trial","pending","suspended","cancelled"];

export default function MasterSubscriptionsPage(){
  const[subscriptions,setSubscriptions]=useState<Subscription[]>([]);const[businesses,setBusinesses]=useState<Business[]>([]);const[statements,setStatements]=useState<Statement[]>([]);const[selectedStatement,setSelectedStatement]=useState<Statement|null>(null);const[loading,setLoading]=useState(true);const[savingId,setSavingId]=useState<string|null>(null);const[message,setMessage]=useState("");const[search,setSearch]=useState("");const[statusFilter,setStatusFilter]=useState("all");const[page,setPage]=useState(1);
  async function loadBilling(){setLoading(true);setMessage("");const[subResult,businessResult,statementResult]=await Promise.all([supabase.from("subscriptions").select("id,business_id,plan_name,monthly_fee,setup_fee,setup_paid,subscription_status,created_at").order("created_at",{ascending:false}),supabase.from("businesses").select("id,business_name,status").neq("status","deleted"),supabase.from("subscription_statements").select("id,subscription_id,statement_type,statement_month,amount,status,recipient_email,paid_at,emailed_at,payment_reference,created_at").order("created_at",{ascending:false})]);if(subResult.error||businessResult.error||statementResult.error){setMessage(subResult.error?.message||businessResult.error?.message||statementResult.error?.message||"Billing records could not be loaded.");setSubscriptions([]);setBusinesses([]);setStatements([]);}else{setSubscriptions(subResult.data||[]);setBusinesses(businessResult.data||[]);setStatements(statementResult.data||[]);}setLoading(false);}
  useEffect(()=>{loadBilling();},[]);
  const rows=useMemo<BillingRow[]>(()=>{const names=new Map(businesses.map(item=>[item.id,item]));return subscriptions.map(item=>{const business=item.business_id?names.get(item.business_id):undefined;return{...item,businessName:business?.business_name||"Business record unavailable",businessStatus:business?.status||null};});},[subscriptions,businesses]);
  const filtered=useMemo(()=>rows.filter(item=>{const query=search.trim().toLowerCase();return(!query||`${item.businessName} ${item.plan_name||""}`.toLowerCase().includes(query))&&(statusFilter==="all"||item.subscription_status===statusFilter);}),[rows,search,statusFilter]);
  const summary=useMemo(()=>({active:rows.filter(x=>x.subscription_status==="active").length,setupDue:rows.filter(x=>!x.setup_paid).length,suspended:rows.filter(x=>x.subscription_status==="suspended").length,monthly:rows.filter(x=>x.subscription_status==="active").reduce((sum,x)=>sum+Number(x.monthly_fee||0),0)}),[rows]);
  const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));const visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  function updateLocal(id:string,field:keyof Subscription,value:string|number|boolean){setSubscriptions(items=>items.map(item=>item.id===id?{...item,[field]:value}:item));}
  function changePlan(id:string,plan:string){const monthlyFee=planFees[plan as keyof typeof planFees];setSubscriptions(items=>items.map(item=>item.id===id?{...item,plan_name:plan,monthly_fee:monthlyFee??item.monthly_fee,setup_fee:monthlyFee===0?0:249}:item));}
  async function save(item:BillingRow){setSavingId(item.id);setMessage("");const{error}=await supabase.from("subscriptions").update({plan_name:item.plan_name,monthly_fee:Number(item.monthly_fee||0),setup_fee:Number(item.setup_fee||0),setup_paid:Boolean(item.setup_paid),subscription_status:item.subscription_status}).eq("id",item.id);setMessage(error?error.message:`Billing updated for ${item.businessName}.`);setSavingId(null);if(!error)await loadBilling();}
  async function markPaid(statement:Statement){setSavingId(statement.id);setMessage("");const{data:{session}}=await supabase.auth.getSession();const response=await fetch("/api/billing/statements/mark-paid",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify({statementId:statement.id})});const result=await response.json().catch(()=>null);setMessage(response.ok?(result?.emailed?"Payment recorded and statement emailed.":"Payment recorded, but the statement email could not be sent."):(result?.error||"Payment could not be recorded."));setSavingId(null);if(response.ok)await loadBilling();}
  async function resendStatement(statement:Statement){setSavingId(statement.id);setMessage("");const{data:{session}}=await supabase.auth.getSession();const response=await fetch("/api/billing/statements/resend",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify({statementId:statement.id})});const result=await response.json().catch(()=>null);setMessage(response.ok&&result?.emailed?"Statement resent successfully.":(result?.error||result?.reason||"Statement could not be resent."));setSavingId(null);if(response.ok)await loadBilling();}
  return <main style={pageStyle}>
    <section style={header}><div><p style={eyebrow}>Platform billing</p><h1 style={title}>Billing & Subscriptions</h1><p style={subtitle}>Manage client plans, setup fees and subscription status without opening payroll or employee records.</p></div><div style={headerActions}><Link href="/master" style={backButton}>← Back to overview</Link><button onClick={loadBilling} style={secondaryButton}>Refresh</button></div></section>
    <section style={summaryGrid}><Summary label="Active subscriptions" value={String(summary.active)} note="Current paying clients"/><Summary label="Monthly recurring" value={`R ${summary.monthly.toFixed(2)}`} note="Based on active plans"/><Summary label="Setup fees due" value={String(summary.setupDue)} note="Not marked as paid"/><Summary label="Suspended" value={String(summary.suspended)} note="Billing access paused"/></section>
    <section style={card}>
      <div style={cardHeader}><div><h2 style={cardTitle}>Client billing</h2><p style={cardText}>Search, review and update one client billing record at a time.</p></div><div style={filters}><input style={searchInput} placeholder="Search business or plan" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><select style={filterSelect} value={statusFilter} onChange={e=>{setStatusFilter(e.target.value);setPage(1);}}><option value="all">All statuses</option>{statuses.map(status=><option key={status} value={status}>{label(status)}</option>)}</select></div></div>
      {message&&<div style={notice}>{message}</div>}
      {loading?<div style={empty}>Loading billing records…</div>:visible.length===0?<div style={empty}>No billing records match your filters.</div>:<><div style={tableWrap}><table style={table}><thead><tr><th style={th}>Client</th><th style={th}>Plan</th><th style={th}>Monthly fee</th><th style={th}>Setup fee</th><th style={th}>Setup paid</th><th style={th}>Status</th><th style={th}>Action</th></tr></thead><tbody>{visible.map(item=>{const statement=statements.find(entry=>entry.subscription_id===item.id&&entry.status!=="emailed");const billable=planFees[item.plan_name as keyof typeof planFees]>0;return <tr key={item.id}><td style={td}><strong>{item.businessName}</strong><span style={subText}>{item.businessStatus?`Business: ${label(item.businessStatus)}`:"Business link unavailable"}</span></td><td style={td}><select style={control} value={item.plan_name||""} onChange={e=>changePlan(item.id,e.target.value)}><option value="">Free / not billed</option>{plans.map(plan=><option key={plan}>{plan}</option>)}</select><span style={subText}>{billable?"Billable plan":"No statements will be created"}</span></td><td style={td}><MoneyInput value={Number(item.monthly_fee||0)} onChange={value=>updateLocal(item.id,"monthly_fee",value)}/></td><td style={td}><MoneyInput value={Number(item.setup_fee||0)} onChange={value=>updateLocal(item.id,"setup_fee",value)}/></td><td style={td}><select style={control} value={item.setup_paid?"yes":"no"} onChange={e=>updateLocal(item.id,"setup_paid",e.target.value==="yes")}><option value="no">Due</option><option value="yes">Paid</option></select></td><td style={td}><select style={control} value={item.subscription_status||"pending"} onChange={e=>updateLocal(item.id,"subscription_status",e.target.value)}>{statuses.map(status=><option key={status} value={status}>{label(status)}</option>)}</select></td><td style={td}><button style={saveButton} disabled={savingId===item.id} onClick={()=>save(item)}>{savingId===item.id?"Saving…":"Save"}</button>{statement&&<button style={statementButton} disabled={savingId===statement.id} onClick={()=>markPaid(statement)}>{savingId===statement.id?"Sending…":`Mark ${statement.statement_type} paid & email`}</button>}<Link href={`/master/businesses/${item.business_id}`} style={detailsLink}>Client details</Link></td></tr>})}</tbody></table></div><Pagination page={page} totalPages={pages} onPageChange={setPage} totalItems={filtered.length} pageSize={PAGE_SIZE}/></>}
    </section>
    <section style={statementCard}>
      <div style={cardHeader}><div><h2 style={cardTitle}>Statement history</h2><p style={cardText}>View every billing statement and resend a paid statement to the recorded business email.</p></div></div>
      {selectedStatement&&<StatementPreview statement={selectedStatement} businessName={rows.find(item=>item.id===selectedStatement.subscription_id)?.businessName||"Business record unavailable"} onClose={()=>setSelectedStatement(null)}/>}
      {loading?<div style={empty}>Loading statements…</div>:statements.length===0?<div style={empty}>No statements have been created yet.</div>:<div style={tableWrap}><table style={table}><thead><tr><th style={th}>Client</th><th style={th}>Statement</th><th style={th}>Amount</th><th style={th}>Billing month</th><th style={th}>Status</th><th style={th}>Actions</th></tr></thead><tbody>{statements.map(statement=>{const businessName=rows.find(item=>item.id===statement.subscription_id)?.businessName||"Business record unavailable";return <tr key={statement.id}><td style={td}><strong>{businessName}</strong><span style={subText}>{statement.recipient_email||"No billing email"}</span></td><td style={td}>{label(statement.statement_type)}</td><td style={td}>R {Number(statement.amount).toFixed(2)}</td><td style={td}>{new Date(`${statement.statement_month}T00:00:00`).toLocaleDateString("en-ZA",{month:"short",year:"numeric"})}</td><td style={td}>{label(statement.status)}</td><td style={td}><button style={statementButton} onClick={()=>setSelectedStatement(statement)}>View</button>{statement.paid_at&&<button style={statementButton} disabled={savingId===statement.id} onClick={()=>resendStatement(statement)}>{savingId===statement.id?"Sending…":"Resend"}</button>}</td></tr>})}</tbody></table></div>}
    </section>
  </main>;
}

function MoneyInput({value,onChange}:{value:number;onChange:(value:number)=>void}){return <div style={moneyWrap}><span>R</span><input style={moneyInput} type="number" min="0" step="0.01" value={value} onChange={e=>onChange(Number(e.target.value))}/></div>}
function Summary({label:heading,value,note}:{label:string;value:string;note:string}){return <article style={summaryCard}><span style={summaryLabel}>{heading}</span><strong style={summaryValue}>{value}</strong><small style={summaryNote}>{note}</small></article>}
function label(value:string){return value.charAt(0).toUpperCase()+value.slice(1).replaceAll("_"," ");}
function StatementPreview({statement,businessName,onClose}:{statement:Statement;businessName:string;onClose:()=>void}){return <aside style={statementPreview}><div><strong>{businessName}</strong><span style={subText}>{statement.recipient_email||"No billing email recorded"}</span></div><button style={previewClose} onClick={onClose}>Close</button><p style={previewTitle}>WageFlow payment statement</p><p style={previewText}>{label(statement.statement_type)} payment for {new Date(`${statement.statement_month}T00:00:00`).toLocaleDateString("en-ZA",{month:"long",year:"numeric"})}: <strong>R {Number(statement.amount).toFixed(2)}</strong></p><p style={previewText}>Status: {label(statement.status)}{statement.paid_at?` • Paid ${new Date(statement.paid_at).toLocaleDateString("en-ZA")}`:""}{statement.payment_reference?` • Reference ${statement.payment_reference}`:""}</p></aside>}
const pageStyle={minHeight:"100vh",padding:38,fontFamily:"Arial, sans-serif",background:"#f4f8fb",color:"#0f172a"};
const header={display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:20,flexWrap:"wrap" as const,marginBottom:26};const eyebrow={margin:"0 0 7px",color:"#b7791f",fontWeight:900,textTransform:"uppercase" as const,letterSpacing:".09em",fontSize:11};const title={margin:"0 0 9px",fontSize:34,color:"#0b6158",fontWeight:900};const subtitle={margin:0,maxWidth:760,color:"#64748b",lineHeight:1.6};
const secondaryButton={border:"1px solid #0f766e",borderRadius:10,padding:"10px 16px",background:"#fff",color:"#0f766e",fontWeight:800,cursor:"pointer"};const summaryGrid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:15,marginBottom:24};const summaryCard={display:"grid",gap:7,padding:19,border:"1px solid #dfe7ed",borderRadius:16,background:"#fff",boxShadow:"0 8px 24px rgba(15,23,42,.04)"};const summaryLabel={color:"#64748b",fontSize:11,fontWeight:900,textTransform:"uppercase" as const};const summaryValue={color:"#0b6158",fontSize:27};const summaryNote={color:"#94a3b8",fontSize:12};
const card={padding:22,border:"1px solid #dfe7ed",borderRadius:18,background:"#fff"};const cardHeader={display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:18,flexWrap:"wrap" as const,marginBottom:18};const cardTitle={margin:"0 0 5px",fontSize:21};const cardText={margin:0,color:"#64748b",fontSize:13};const filters={display:"flex",gap:10,flexWrap:"wrap" as const};const searchInput={minWidth:240,padding:"10px 12px",border:"1px solid #cbd5e1",borderRadius:9};const filterSelect={padding:"10px 12px",border:"1px solid #cbd5e1",borderRadius:9,background:"#fff"};const notice={padding:12,marginBottom:14,borderRadius:10,background:"#ecfeff",color:"#155e75",fontWeight:700,fontSize:13};const empty={padding:30,textAlign:"center" as const,color:"#64748b"};const tableWrap={overflowX:"auto" as const};const table={width:"100%",borderCollapse:"collapse" as const};const th={padding:"11px 10px",background:"#f7fafc",borderBottom:"1px solid #e2e8f0",textAlign:"left" as const,color:"#475569",fontSize:11,textTransform:"uppercase" as const};const td={padding:"12px 10px",borderBottom:"1px solid #e2e8f0",verticalAlign:"top" as const,minWidth:125};const subText={display:"block",marginTop:5,color:"#94a3b8",fontSize:11};const control={width:"100%",padding:"9px 10px",border:"1px solid #cbd5e1",borderRadius:8,background:"#fff"};const moneyWrap={display:"flex",alignItems:"center",border:"1px solid #cbd5e1",borderRadius:8,overflow:"hidden"};const moneyInput={width:90,padding:"9px 8px",border:0,outline:0};const saveButton={width:"100%",padding:"9px 13px",border:0,borderRadius:8,background:"#0f766e",color:"#fff",fontWeight:800,cursor:"pointer"};const detailsLink={display:"block",marginTop:8,color:"#0f766e",fontSize:11,fontWeight:700,textAlign:"center" as const,textDecoration:"none"};
const statementButton={width:"100%",marginTop:8,padding:"9px 10px",border:"1px solid #0f766e",borderRadius:8,background:"#fff",color:"#0f766e",fontWeight:800,cursor:"pointer",fontSize:11};
const headerActions={display:"flex",gap:10,alignItems:"center",flexWrap:"wrap" as const};const backButton={border:"1px solid #0f766e",borderRadius:10,padding:"10px 14px",background:"#fff",color:"#0f766e",fontWeight:800,textDecoration:"none",fontSize:13};const statementCard={...card,marginTop:24};const statementPreview={display:"grid",gridTemplateColumns:"1fr auto",gap:8,marginBottom:18,padding:16,border:"1px solid #99f6e4",borderRadius:12,background:"#f0fdfa"};const previewClose={border:0,background:"transparent",color:"#0f766e",fontWeight:800,cursor:"pointer"};const previewTitle={gridColumn:"1 / -1",margin:"6px 0 0",color:"#0f4f49",fontWeight:900};const previewText={gridColumn:"1 / -1",margin:0,color:"#475569",fontSize:13};
