"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { supabase } from "@/app/lib/supabaseClient";
import { Pagination } from "@/components/Pagination";

type Subscription = { id:string; business_id:string|null; plan_name:string|null; monthly_fee:number|null; setup_fee:number|null; setup_paid:boolean|null; subscription_status:string|null; created_at?:string|null };
type Business = { id:string; business_name:string; status:string|null };
type BillingRow = Subscription & { businessName:string; businessStatus:string|null };
const PAGE_SIZE=8;
const plans=["Starter","Growth"];
const statuses=["active","trial","pending","suspended","cancelled"];

export default function MasterSubscriptionsPage(){
  const[subscriptions,setSubscriptions]=useState<Subscription[]>([]);const[businesses,setBusinesses]=useState<Business[]>([]);const[loading,setLoading]=useState(true);const[savingId,setSavingId]=useState<string|null>(null);const[message,setMessage]=useState("");const[search,setSearch]=useState("");const[statusFilter,setStatusFilter]=useState("all");const[page,setPage]=useState(1);
  async function loadBilling(){setLoading(true);setMessage("");const[subResult,businessResult]=await Promise.all([supabase.from("subscriptions").select("id,business_id,plan_name,monthly_fee,setup_fee,setup_paid,subscription_status,created_at").order("created_at",{ascending:false}),supabase.from("businesses").select("id,business_name,status").neq("status","deleted")]);if(subResult.error||businessResult.error){setMessage(subResult.error?.message||businessResult.error?.message||"Billing records could not be loaded.");setSubscriptions([]);setBusinesses([]);}else{setSubscriptions(subResult.data||[]);setBusinesses(businessResult.data||[]);}setLoading(false);}
  useEffect(()=>{loadBilling();},[]);
  const rows=useMemo<BillingRow[]>(()=>{const names=new Map(businesses.map(item=>[item.id,item]));return subscriptions.map(item=>{const business=item.business_id?names.get(item.business_id):undefined;return{...item,businessName:business?.business_name||"Business record unavailable",businessStatus:business?.status||null};});},[subscriptions,businesses]);
  const filtered=useMemo(()=>rows.filter(item=>{const query=search.trim().toLowerCase();return(!query||`${item.businessName} ${item.plan_name||""}`.toLowerCase().includes(query))&&(statusFilter==="all"||item.subscription_status===statusFilter);}),[rows,search,statusFilter]);
  const summary=useMemo(()=>({active:rows.filter(x=>x.subscription_status==="active").length,setupDue:rows.filter(x=>!x.setup_paid).length,suspended:rows.filter(x=>x.subscription_status==="suspended").length,monthly:rows.filter(x=>x.subscription_status==="active").reduce((sum,x)=>sum+Number(x.monthly_fee||0),0)}),[rows]);
  const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));const visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  function updateLocal(id:string,field:keyof Subscription,value:string|number|boolean){setSubscriptions(items=>items.map(item=>item.id===id?{...item,[field]:value}:item));}
  async function save(item:BillingRow){setSavingId(item.id);setMessage("");const{error}=await supabase.from("subscriptions").update({plan_name:item.plan_name,monthly_fee:Number(item.monthly_fee||0),setup_fee:Number(item.setup_fee||0),setup_paid:Boolean(item.setup_paid),subscription_status:item.subscription_status}).eq("id",item.id);setMessage(error?error.message:`Billing updated for ${item.businessName}.`);setSavingId(null);if(!error)await loadBilling();}
  return <main style={pageStyle}>
    <section style={header}><div><p style={eyebrow}>Platform billing</p><h1 style={title}>Billing & Subscriptions</h1><p style={subtitle}>Manage client plans, setup fees and subscription status without opening payroll or employee records.</p></div><button onClick={loadBilling} style={secondaryButton}>Refresh</button></section>
    <section style={summaryGrid}><Summary label="Active subscriptions" value={String(summary.active)} note="Current paying clients"/><Summary label="Monthly recurring" value={`R ${summary.monthly.toFixed(2)}`} note="Based on active plans"/><Summary label="Setup fees due" value={String(summary.setupDue)} note="Not marked as paid"/><Summary label="Suspended" value={String(summary.suspended)} note="Billing access paused"/></section>
    <section style={card}>
      <div style={cardHeader}><div><h2 style={cardTitle}>Client billing</h2><p style={cardText}>Search, review and update one client billing record at a time.</p></div><div style={filters}><input style={searchInput} placeholder="Search business or plan" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><select style={filterSelect} value={statusFilter} onChange={e=>{setStatusFilter(e.target.value);setPage(1);}}><option value="all">All statuses</option>{statuses.map(status=><option key={status} value={status}>{label(status)}</option>)}</select></div></div>
      {message&&<div style={notice}>{message}</div>}
      {loading?<div style={empty}>Loading billing records…</div>:visible.length===0?<div style={empty}>No billing records match your filters.</div>:<><div style={tableWrap}><table style={table}><thead><tr><th style={th}>Client</th><th style={th}>Plan</th><th style={th}>Monthly fee</th><th style={th}>Setup fee</th><th style={th}>Setup paid</th><th style={th}>Status</th><th style={th}>Action</th></tr></thead><tbody>{visible.map(item=><tr key={item.id}><td style={td}><strong>{item.businessName}</strong><span style={subText}>{item.businessStatus?`Business: ${label(item.businessStatus)}`:"Business link unavailable"}</span></td><td style={td}><select style={control} value={item.plan_name||""} onChange={e=>updateLocal(item.id,"plan_name",e.target.value)}><option value="">Select plan</option>{plans.map(plan=><option key={plan}>{plan}</option>)}</select></td><td style={td}><MoneyInput value={Number(item.monthly_fee||0)} onChange={value=>updateLocal(item.id,"monthly_fee",value)}/></td><td style={td}><MoneyInput value={Number(item.setup_fee||0)} onChange={value=>updateLocal(item.id,"setup_fee",value)}/></td><td style={td}><select style={control} value={item.setup_paid?"yes":"no"} onChange={e=>updateLocal(item.id,"setup_paid",e.target.value==="yes")}><option value="no">Due</option><option value="yes">Paid</option></select></td><td style={td}><select style={control} value={item.subscription_status||"pending"} onChange={e=>updateLocal(item.id,"subscription_status",e.target.value)}>{statuses.map(status=><option key={status} value={status}>{label(status)}</option>)}</select></td><td style={td}><button style={saveButton} disabled={savingId===item.id} onClick={()=>save(item)}>{savingId===item.id?"Saving…":"Save"}</button><Link href={`/master/businesses/${item.business_id}`} style={detailsLink}>Client details</Link></td></tr>)}</tbody></table></div><Pagination page={page} totalPages={pages} onPageChange={setPage} totalItems={filtered.length} pageSize={PAGE_SIZE}/></>}
    </section>
  </main>;
}

function MoneyInput({value,onChange}:{value:number;onChange:(value:number)=>void}){return <div style={moneyWrap}><span>R</span><input style={moneyInput} type="number" min="0" step="0.01" value={value} onChange={e=>onChange(Number(e.target.value))}/></div>}
function Summary({label:heading,value,note}:{label:string;value:string;note:string}){return <article style={summaryCard}><span style={summaryLabel}>{heading}</span><strong style={summaryValue}>{value}</strong><small style={summaryNote}>{note}</small></article>}
function label(value:string){return value.charAt(0).toUpperCase()+value.slice(1).replaceAll("_"," ");}
const pageStyle={minHeight:"100vh",padding:38,fontFamily:"Arial, sans-serif",background:"#f4f8fb",color:"#0f172a"};
const header={display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:20,flexWrap:"wrap" as const,marginBottom:26};const eyebrow={margin:"0 0 7px",color:"#b7791f",fontWeight:900,textTransform:"uppercase" as const,letterSpacing:".09em",fontSize:11};const title={margin:"0 0 9px",fontSize:34,color:"#0b6158",fontWeight:900};const subtitle={margin:0,maxWidth:760,color:"#64748b",lineHeight:1.6};
const secondaryButton={border:"1px solid #0f766e",borderRadius:10,padding:"10px 16px",background:"#fff",color:"#0f766e",fontWeight:800,cursor:"pointer"};const summaryGrid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:15,marginBottom:24};const summaryCard={display:"grid",gap:7,padding:19,border:"1px solid #dfe7ed",borderRadius:16,background:"#fff",boxShadow:"0 8px 24px rgba(15,23,42,.04)"};const summaryLabel={color:"#64748b",fontSize:11,fontWeight:900,textTransform:"uppercase" as const};const summaryValue={color:"#0b6158",fontSize:27};const summaryNote={color:"#94a3b8",fontSize:12};
const card={padding:22,border:"1px solid #dfe7ed",borderRadius:18,background:"#fff"};const cardHeader={display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:18,flexWrap:"wrap" as const,marginBottom:18};const cardTitle={margin:"0 0 5px",fontSize:21};const cardText={margin:0,color:"#64748b",fontSize:13};const filters={display:"flex",gap:10,flexWrap:"wrap" as const};const searchInput={minWidth:240,padding:"10px 12px",border:"1px solid #cbd5e1",borderRadius:9};const filterSelect={padding:"10px 12px",border:"1px solid #cbd5e1",borderRadius:9,background:"#fff"};const notice={padding:12,marginBottom:14,borderRadius:10,background:"#ecfeff",color:"#155e75",fontWeight:700,fontSize:13};const empty={padding:30,textAlign:"center" as const,color:"#64748b"};const tableWrap={overflowX:"auto" as const};const table={width:"100%",borderCollapse:"collapse" as const};const th={padding:"11px 10px",background:"#f7fafc",borderBottom:"1px solid #e2e8f0",textAlign:"left" as const,color:"#475569",fontSize:11,textTransform:"uppercase" as const};const td={padding:"12px 10px",borderBottom:"1px solid #e2e8f0",verticalAlign:"top" as const,minWidth:125};const subText={display:"block",marginTop:5,color:"#94a3b8",fontSize:11};const control={width:"100%",padding:"9px 10px",border:"1px solid #cbd5e1",borderRadius:8,background:"#fff"};const moneyWrap={display:"flex",alignItems:"center",border:"1px solid #cbd5e1",borderRadius:8,overflow:"hidden"};const moneyInput={width:90,padding:"9px 8px",border:0,outline:0};const saveButton={width:"100%",padding:"9px 13px",border:0,borderRadius:8,background:"#0f766e",color:"#fff",fontWeight:800,cursor:"pointer"};const detailsLink={display:"block",marginTop:8,color:"#0f766e",fontSize:11,fontWeight:700,textAlign:"center" as const,textDecoration:"none"};
