import type { CSSProperties } from "react";

type PayslipItem = {
  item: string;
  amount: number;
};

type PayslipData = {
  company: {
    name: string;
    logoUrl: string;
    address: string;
    registrationNumber: string;
    payeReference: string;
    uifReference: string;
    phone: string;
    email: string;
  };
  employee: {
    name: string;
    employeeNumber: string;
    position: string;
    department: string;
    idNumber: string;
    paymentMethod: string;
    bankName: string;
    accountNumber: string;
  };
  pay: {
    period: string;
    payDate: string;
    payReference: string;
  };
  earnings: PayslipItem[];
  deductions: PayslipItem[];
  ytd: {
    from: string;
    to: string;
    gross: number;
    taxable: number;
    paye: number;
    uif: number;
  };
  leave: {
    annual: number;
  };
};

export default function PayslipTemplate({ payslip }: { payslip: PayslipData }) {
  const grossPay = payslip.earnings.reduce((sum, row) => sum + row.amount, 0);

  const totalDeductions = payslip.deductions.reduce(
    (sum, row) => sum + row.amount,
    0
  );

  const netPay = grossPay - totalDeductions;

  const money = (amount: number) =>
    `R${amount.toLocaleString("en-ZA", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`;

  return (
    <section style={sheet}>
      <img src={payslip.company.logoUrl} alt="" style={watermark} />

      <div style={content}>
        <header style={header}>
          <div style={companyLogo}>
            <img
              src={payslip.company.logoUrl}
              alt={`${payslip.company.name} logo`}
              style={logoImage}
            />
          </div>

          <div>
            <h1 style={title}>Payslip</h1>
            <p style={subtitle}>Pay period: {payslip.pay.period}</p>
          </div>
        </header>

        <section style={detailsGrid}>
          <div style={detailsBox}>
            <h3 style={sectionTitle}>Employer Details</h3>
            <p style={strong}>{payslip.company.name}</p>
            <p>{payslip.company.address}</p>
            <p>Reg No: {payslip.company.registrationNumber}</p>
            <p>PAYE Ref: {payslip.company.payeReference}</p>
            <p>UIF Ref: {payslip.company.uifReference}</p>
            <p>Phone: {payslip.company.phone}</p>
            <p>Email: {payslip.company.email}</p>
          </div>

          <div style={detailsBox}>
            <h3 style={sectionTitle}>Employee Details</h3>
            <Info label="Employee Name" value={payslip.employee.name} />
            <Info label="Employee No." value={payslip.employee.employeeNumber} />
            <Info label="ID Number" value={payslip.employee.idNumber} />
            <Info label="Position" value={payslip.employee.position} />
            <Info label="Department" value={payslip.employee.department} />
            <Info label="Payment Method" value={payslip.employee.paymentMethod} />
            <Info label="Bank" value={payslip.employee.bankName} />
            <Info label="Account No." value={payslip.employee.accountNumber} />
          </div>
        </section>

        <section style={summaryGrid}>
          <Summary label="Pay Date" value={payslip.pay.payDate} />
          <Summary label="Pay Reference" value={payslip.pay.payReference} />
          <Summary label="Gross Pay" value={money(grossPay)} />
          <Summary label="Deductions" value={money(totalDeductions)} />
          <Summary label="Net Pay" value={money(netPay)} highlight />
        </section>

        <section style={tableGrid}>
          <Table title="Earnings" rows={payslip.earnings} total={grossPay} money={money} />
          <Table title="Deductions" rows={payslip.deductions} total={totalDeductions} money={money} />
        </section>

        <section style={ytdBox}>
          <h3 style={ytdTitle}>
            Year to Date Payroll Summary: {payslip.ytd.from} - {payslip.ytd.to}
          </h3>

          <div style={ytdGrid}>
            <Ytd label="YTD Gross Pay" value={money(payslip.ytd.gross)} />
            <Ytd label="YTD Taxable Pay" value={money(payslip.ytd.taxable)} />
            <Ytd label="YTD PAYE" value={money(payslip.ytd.paye)} />
            <Ytd label="YTD UIF" value={money(payslip.ytd.uif)} />
          </div>
        </section>

        <section style={leaveBox}>
          <h3 style={sectionTitle}>Leave Balances</h3>
          <div style={leaveGrid}>
            <div style={leaveItem}>
              <span>Annual Leave</span>
              <strong>{payslip.leave.annual} days</strong>
            </div>
          </div>
        </section>

        <section style={netBox}>
          <div>
            <h2 style={netTitle}>Net Pay This Period</h2>
            <p style={netSubtext}>Payable via {payslip.employee.paymentMethod}</p>
          </div>

          <strong style={netAmount}>{money(netPay)}</strong>
        </section>

        <section style={footerBox}>
          <p>
            Generated by <strong>WageFlow Payroll Assistant</strong>, a product
            of <strong> Lesedi Smart Solutions (Pty) Ltd</strong>.
          </p>

          <p>
            WageFlow is a payslip generation and employee record-keeping tool.
            It does not act as the employer, payroll bureau, accountant or
            registered tax practitioner.
          </p>

          <p style={generatedNote}>
            This is a computer-generated payslip and does not require a signature.
          </p>
        </section>
      </div>
    </section>
  );
}

function Info({ label, value }: { label: string; value: string }) {
  return (
    <p style={infoRow}>
      <span style={infoLabel}>{label}</span>
      <span>{value}</span>
    </p>
  );
}

function Summary({
  label,
  value,
  highlight,
}: {
  label: string;
  value: string;
  highlight?: boolean;
}) {
  return (
    <div style={summaryCard}>
      <p style={summaryLabel}>{label}</p>
      <strong style={highlight ? summaryHighlight : summaryValue}>{value}</strong>
    </div>
  );
}

function Table({
  title,
  rows,
  total,
  money,
}: {
  title: string;
  rows: PayslipItem[];
  total: number;
  money: (amount: number) => string;
}) {
  return (
    <div style={tableBox}>
      <div style={tableHeader}>
        <span>{title}</span>
        <span>Amount</span>
      </div>

      {rows.map((row) => (
        <div style={tableRow} key={row.item}>
          <span>{row.item}</span>
          <span>{money(row.amount)}</span>
        </div>
      ))}

      <div style={totalRow}>
        <span>Total {title}</span>
        <span>{money(total)}</span>
      </div>
    </div>
  );
}

function Ytd({ label, value }: { label: string; value: string }) {
  return (
    <div style={ytdItem}>
      <span>{label}</span>
      <strong>{value}</strong>
    </div>
  );
}

const sheet: CSSProperties = {
  position: "relative",
  overflow: "hidden",
  maxWidth: "1050px",
  margin: "0 auto",
  background: "#ffffff",
  borderRadius: "22px",
  padding: "34px",
  boxShadow: "0 20px 60px rgba(16, 72, 84, 0.12)",
  border: "1px solid #d8eeee",
};

const content: CSSProperties = {
  position: "relative",
  zIndex: 1,
};

const watermark: CSSProperties = {
  position: "absolute",
  top: "46%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: "460px",
  maxWidth: "75%",
  opacity: 0.055,
  zIndex: 0,
  pointerEvents: "none",
};

const header: CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  gap: "24px",
  borderBottom: "1px solid #d8eeee",
  paddingBottom: "24px",
  marginBottom: "28px",
};

const companyLogo: CSSProperties = {
  width: "180px",
  height: "90px",
  borderRadius: "18px",
  background: "#ffffff",
  border: "1px solid #d8eeee",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  padding: "12px",
};

const logoImage: CSSProperties = {
  maxWidth: "100%",
  maxHeight: "100%",
  objectFit: "contain",
};

const title: CSSProperties = {
  margin: 0,
  color: "#176f7a",
  fontSize: "34px",
  textTransform: "uppercase",
  textAlign: "right",
};

const subtitle: CSSProperties = {
  margin: "8px 0 0",
  fontSize: "16px",
  textAlign: "right",
};

const detailsGrid: CSSProperties = {
  display: "grid",
  gridTemplateColumns: "1fr 1fr",
  gap: "22px",
  marginBottom: "24px",
};

const detailsBox: CSSProperties = {
  background: "rgba(247, 252, 252, 0.92)",
  border: "1px solid #d8eeee",
  borderRadius: "18px",
  padding: "22px",
  lineHeight: 1.7,
};

const sectionTitle: CSSProperties = {
  margin: "0 0 12px",
  color: "#176f7a",
  textTransform: "uppercase",
  fontSize: "15px",
  letterSpacing: "0.5px",
};

const strong: CSSProperties = {
  fontWeight: 800,
};

const infoRow: CSSProperties = {
  display: "grid",
  gridTemplateColumns: "150px 1fr",
  margin: "4px 0",
};

const infoLabel: CSSProperties = {
  fontWeight: 700,
  color: "#4c586d",
};

const summaryGrid: CSSProperties = {
  display: "grid",
  gridTemplateColumns: "repeat(5, 1fr)",
  gap: "12px",
  marginBottom: "24px",
};

const summaryCard: CSSProperties = {
  border: "1px solid #d8eeee",
  borderRadius: "16px",
  padding: "18px",
  background: "rgba(255, 255, 255, 0.94)",
  textAlign: "center",
};

const summaryLabel: CSSProperties = {
  margin: "0 0 8px",
  color: "#176f7a",
  fontWeight: 800,
  fontSize: "13px",
  textTransform: "uppercase",
};

const summaryValue: CSSProperties = {
  fontSize: "17px",
  color: "#172033",
};

const summaryHighlight: CSSProperties = {
  fontSize: "20px",
  color: "#176f7a",
};

const tableGrid: CSSProperties = {
  display: "grid",
  gridTemplateColumns: "1fr 1fr",
  gap: "24px",
  marginBottom: "24px",
};

const tableBox: CSSProperties = {
  border: "1px solid #d8eeee",
  borderRadius: "18px",
  overflow: "hidden",
  background: "rgba(255, 255, 255, 0.94)",
};

const tableHeader: CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  padding: "14px 18px",
  background: "#176f7a",
  color: "#ffffff",
  fontWeight: 800,
  textTransform: "uppercase",
};

const tableRow: CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  padding: "14px 18px",
  borderBottom: "1px solid #eef6f6",
};

const totalRow: CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  padding: "16px 18px",
  fontWeight: 900,
  color: "#176f7a",
  background: "#f7fcfc",
  textTransform: "uppercase",
};

const ytdBox: CSSProperties = {
  border: "1px solid #d8eeee",
  borderRadius: "18px",
  padding: "18px 22px",
  marginBottom: "24px",
  background: "rgba(247, 252, 252, 0.94)",
};

const ytdTitle: CSSProperties = {
  margin: "0 0 14px",
  color: "#176f7a",
  fontSize: "15px",
  textTransform: "uppercase",
  fontWeight: 800,
  textAlign: "center",
};

const ytdGrid: CSSProperties = {
  display: "grid",
  gridTemplateColumns: "repeat(4, 1fr)",
  gap: "12px",
};

const ytdItem: CSSProperties = {
  textAlign: "center",
  fontSize: "13px",
  color: "#4c586d",
  display: "flex",
  flexDirection: "column",
  gap: "4px",
};

const leaveBox: CSSProperties = {
  border: "1px solid #d8eeee",
  borderRadius: "18px",
  padding: "18px 22px",
  marginBottom: "24px",
  background: "rgba(247, 252, 252, 0.94)",
};

const leaveGrid: CSSProperties = {
  display: "flex",
  gap: "30px",
  marginTop: "10px",
};

const leaveItem: CSSProperties = {
  display: "flex",
  flexDirection: "column",
  fontSize: "14px",
  color: "#4c586d",
};

const netBox: CSSProperties = {
  border: "2px solid #176f7a",
  borderRadius: "18px",
  padding: "18px 24px",
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  marginBottom: "24px",
  background: "rgba(247, 252, 252, 0.94)",
};

const netTitle: CSSProperties = {
  margin: 0,
  color: "#176f7a",
  textTransform: "uppercase",
  fontSize: "18px",
};

const netSubtext: CSSProperties = {
  margin: "6px 0 0",
  color: "#4c586d",
  fontWeight: 700,
  fontSize: "14px",
};

const netAmount: CSSProperties = {
  color: "#176f7a",
  fontSize: "26px",
  lineHeight: 1.1,
};

const footerBox: CSSProperties = {
  borderTop: "1px solid #d8eeee",
  paddingTop: "18px",
  color: "#5b6678",
  fontSize: "13px",
  lineHeight: 1.6,
  textAlign: "center",
};

const generatedNote: CSSProperties = {
  marginTop: "14px",
  color: "#7b8494",
  fontSize: "12px",
};