"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/app/lib/supabaseClient";

type Row = { id: string; employee_id: string; payroll_month: string | null; created_at: string; employees: { full_name: string | null; employee_number: string | null; department: string | null } | null; payslip_distribution_records: { id: string; delivery_status: string; delivered_to: string | null; received_by: string | null; received_at: string | null }[] | null };
const statusLabel: Record<string, string> = { printed: "Printed", handed_to_supervisor: "Handed to supervisor", signed_received: "Signed received" };

export default function PayslipDistributionPage() {
  const [rows, setRows] = useState<Row[]>([]); const [businessId, setBusinessId] = useState(""); const [month, setMonth] = useState(""); const [message, setMessage] = useState("");
  async function load() { const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: profile } = await supabase.from("profiles").select("business_id").eq("id", user.id).maybeSingle(); if (!profile?.business_id) return; setBusinessId(profile.business_id); const { data, error } = await supabase.from("payslips").select("id,employee_id,payroll_month,created_at,employees(full_name,employee_number,department),payslip_distribution_records(id,delivery_status,delivered_to,received_by,received_at)").eq("business_id", profile.business_id).order("payroll_month", { ascending: false }); if (error) setMessage(error.message); else { setRows((data || []) as unknown as Row[]); if (data?.[0]?.payroll_month) setMonth(String(data[0].payroll_month)); } }
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => rows.filter((row) => !month || row.payroll_month === month), [rows, month]); const months = [...new Set(rows.map((row) => row.payroll_month).filter(Boolean))] as string[];
  async function update(row: Row, deliveryStatus: string) { const existing = row.payslip_distribution_records?.[0]; const payload = { business_id: businessId, payslip_id: row.id, employee_id: row.employee_id, delivery_status: deliveryStatus, delivered_at: deliveryStatus === "printed" ? null : new Date().toISOString(), received_at: deliveryStatus === "signed_received" ? new Date().toISOString() : null }; const query = existing ? supabase.from("payslip_distribution_records").update(payload).eq("id", existing.id) : supabase.from("payslip_distribution_records").insert(payload); const { error } = await query; if (error) setMessage(error.message); else await load(); }
  function printRegister() { const cells = visible.map((row) => `<tr><td>${escapeHtml(row.employees?.employee_number || "")}</td><td>${escapeHtml(row.employees?.full_name || "Employee")}</td><td>${escapeHtml(row.employees?.department || "")}</td><td></td><td></td><td></td></tr>`).join(""); const popup = window.open("", "_blank"); if (!popup) { setMessage("Allow pop-ups to print the distribution register."); return; } popup.document.write(`<!doctype html><title>Payslip distribution register</title><style>body{font-family:Arial;margin:30px;color:#111}table{width:100%;border-collapse:collapse}th,td{border:1px solid #555;padding:9px;text-align:left;height:25px}th{background:#eee}@media print{button{display:none}}</style><button onclick="window.print()">Print / Save PDF</button><h1>Payslip distribution register</h1><p>Payroll period: ${escapeHtml(month || "All")}</p><table><thead><tr><th>Employee no.</th><th>Employee</th><th>Department / team</th><th>Received by / supervisor</th><th>Signature / thumbprint</th><th>Date</th></tr></thead><tbody>${cells}</tbody></table>`); popup.document.close(); }
  return <main style={page}><section style={header}><div><p style={eyebrow}>Paper-first payroll</p><h1 style={title}>Payslip distribution</h1><p style={subtitle}>Print a register for paper payslips and record how each payslip was distributed.</p></div><Link href="/employer" style={back}>Back to dashboard</Link></section>{message && <p style={notice}>{message}</p>}<section style={card}><div style={actions}><select style={input} value={month} onChange={(e) => setMonth(e.target.value)}><option value="">All payroll periods</option>{months.map((item) => <option key={item} value={item}>{item}</option>)}</select><button style={button} onClick={printRegister} disabled={!visible.length}>Print distribution register</button></div>{visible.length === 0 ? <p>No payslips found for this period.</p> : <table style={table}><thead><tr><th style={th}>Employee</th><th style={th}>Department</th><th style={th}>Period</th><th style={th}>Delivery status</th><th style={th}>Record</th></tr></thead><tbody>{visible.map((row) => { const record = row.payslip_distribution_records?.[0]; return <tr key={row.id}><td style={td}><strong>{row.employees?.full_name || "Employee"}</strong><br /><small>{row.employees?.employee_number || ""}</small></td><td style={td}>{row.employees?.department || "—"}</td><td style={td}>{row.payroll_month || "—"}</td><td style={td}>{statusLabel[record?.delivery_status || ""] || "Not recorded"}</td><td style={td}><select style={input} value={record?.delivery_status || ""} onChange={(e) => { if (e.target.value) void update(row, e.target.value); }}><option value="">Choose status</option><option value="printed">Printed</option><option value="handed_to_supervisor">Handed to supervisor</option><option value="signed_received">Signed received</option></select></td></tr>; })}</tbody></table>}</section></main>;
}
function escapeHtml(value: string) { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] || character); }
const page={minHeight:"100vh",padding:"38px",background:"#f4f8fb",fontFamily:"Arial, sans-serif",color:"#0f172a"};const header={display:"flex",justifyContent:"space-between",gap:18,marginBottom:24};const eyebrow={margin:0,color:"#0f766e",fontWeight:800,fontSize:12,textTransform:"uppercase" as const};const title={margin:"6px 0",fontSize:32};const subtitle={margin:0,color:"#64748b"};const back={color:"#0f766e",fontWeight:800,textDecoration:"none"};const card={background:"#fff",border:"1px solid #e2e8f0",borderRadius:18,padding:20,overflowX:"auto" as const};const actions={display:"flex",gap:10,marginBottom:18,flexWrap:"wrap" as const};const input={padding:"10px",border:"1px solid #cbd5e1",borderRadius:9,background:"#fff"};const button={background:"#0f766e",color:"#fff",border:0,borderRadius:9,padding:"10px 14px",fontWeight:800,cursor:"pointer"};const table={width:"100%",borderCollapse:"collapse" as const,minWidth:720};const th={textAlign:"left" as const,padding:10,borderBottom:"1px solid #cbd5e1",fontSize:12};const td={padding:10,borderBottom:"1px solid #e2e8f0",verticalAlign:"top" as const};const notice={padding:12,background:"#fff7ed",color:"#9a3412",borderRadius:10};
