"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabaseClient";

type Assignment = { id: string; assigned_at: string; company_policies: { id: string; title: string; version: string; policy_text?: string | null; file_path?: string | null; published_at: string } | null; policy_acknowledgements?: { id: string; acknowledged_at: string }[] };

export default function EmployeePoliciesPage() {
  const [items, setItems] = useState<Assignment[]>([]); const [message, setMessage] = useState("Loading policies…"); const [savingId, setSavingId] = useState("");
  useEffect(() => { void load(); }, []);
  async function request(url: string, init?: RequestInit) { const { data: { session } } = await supabase.auth.getSession(); const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}), Authorization: `Bearer ${session?.access_token || ""}` } }); return { response, body: await response.json().catch(() => ({})) }; }
  async function load() { const { response, body } = await request("/api/policies"); if (!response.ok) setMessage(body.error || "Policies could not be loaded."); else { setItems(body.policies || []); setMessage(""); } }
  async function acknowledge(assignmentId: string) { setSavingId(assignmentId); const { response, body } = await request("/api/policies/acknowledge", { method: "POST", body: JSON.stringify({ assignmentId }) }); setSavingId(""); if (!response.ok) return setMessage(body.error || "Your acknowledgement could not be saved."); setMessage("Thank you. Your acknowledgement has been recorded."); await load(); }
  return <main style={page}><header style={header}><div><p style={eyebrow}>Your workplace documents</p><h1 style={title}>Policies & acknowledgements</h1><p style={subtitle}>Read shared policies and confirm receipt.</p></div><Link href="/employee" style={back}>← Back to Dashboard</Link></header>{message && <p style={notice}>{message}</p>}{!message && items.length === 0 && <section style={card}><p style={muted}>No policies have been assigned to you yet.</p></section>}<section style={list}>{items.map((assignment) => { const policy = assignment.company_policies; const acknowledgement = assignment.policy_acknowledgements?.[0]; if (!policy) return null; return <article key={assignment.id} style={card}><div style={cardHeader}><div><h2 style={heading}>{policy.title}</h2><p style={muted}>Version {policy.version} · Shared {new Date(assignment.assigned_at).toLocaleDateString("en-ZA")}</p></div>{acknowledgement ? <span style={ackBadge}>Acknowledged {new Date(acknowledgement.acknowledged_at).toLocaleDateString("en-ZA")}</span> : <span style={pendingBadge}>Action required</span>}</div>{policy.policy_text && <div style={policyText}>{policy.policy_text}</div>}{policy.file_path && <a href={`/api/policies/${policy.id}/document`} target="_blank" style={documentLink}>Open document</a>}{!acknowledgement && <button style={button} disabled={savingId === assignment.id} onClick={() => void acknowledge(assignment.id)}>{savingId === assignment.id ? "Saving…" : "Acknowledge"}</button>}</article>; })}</section></main>;
}
const page = { minHeight: "100vh", padding: "28px clamp(16px,3vw,42px)", background: "#f4f8fb", color: "#0f172a" }; const header = { display: "flex", justifyContent: "space-between", gap: 16, flexWrap: "wrap" as const, marginBottom: 22 }; const eyebrow = { margin: 0, color: "#b7791f", fontSize: 12, fontWeight: 800, textTransform: "uppercase" as const }; const title = { margin: "5px 0", fontSize: "clamp(26px,3vw,30px)", color: "#0f766e" }; const subtitle = { margin: 0, color: "#64748b", maxWidth: 650, lineHeight: 1.55 }; const back = { alignSelf: "flex-start", padding: "10px 15px", border: "1px solid #0f766e", borderRadius: 10, color: "#0f766e", fontWeight: 800, textDecoration: "none" }; const notice = { background: "#ecfeff", color: "#155e75", padding: 12, borderRadius: 10, fontWeight: 700, marginBottom: 16 }; const list = { display: "grid", gap: 16 }; const card = { background: "#fff", border: "1px solid #e2e8f0", borderRadius: 16, padding: 20, boxShadow: "0 8px 24px rgba(15,23,42,.05)" }; const cardHeader = { display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap" as const, alignItems: "flex-start" }; const heading = { margin: 0, fontSize: 19 }; const muted = { color: "#64748b", margin: "6px 0", lineHeight: 1.5 }; const policyText = { whiteSpace: "pre-wrap" as const, color: "#334155", background: "#f8fafc", padding: 14, borderRadius: 10, lineHeight: 1.65, margin: "14px 0" }; const documentLink = { display: "inline-block", color: "#0f766e", fontWeight: 800, margin: "5px 0 16px" }; const button = { display: "block", padding: "11px 16px", background: "#0f766e", color: "#fff", border: 0, borderRadius: 10, fontWeight: 800, cursor: "pointer" }; const ackBadge = { background: "#ecfdf5", color: "#166534", border: "1px solid #bbf7d0", padding: "7px 10px", borderRadius: 99, fontSize: 12, fontWeight: 800 }; const pendingBadge = { background: "#fff7ed", color: "#9a3412", border: "1px solid #fed7aa", padding: "7px 10px", borderRadius: 99, fontSize: 12, fontWeight: 800 };
