"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/app/lib/supabaseClient";

type ChangeRequest = { id: string; request_type: string; requested_changes: Record<string, string>; status: string; employee_note: string | null; employer_note: string | null; evidence_path: string | null; created_at: string };
const labels: Record<string, string> = { contact: "Contact details", emergency_contact: "Emergency contact", banking: "Banking details" };
const fields: Record<string, { key: string; label: string; type?: string }[]> = {
  contact: [{ key: "email", label: "Email", type: "email" }, { key: "phone", label: "Phone" }, { key: "physical_address", label: "Physical address" }],
  emergency_contact: [{ key: "next_of_kin_name", label: "Contact name" }, { key: "next_of_kin_phone", label: "Contact phone" }, { key: "next_of_kin_relationship", label: "Relationship" }],
  banking: [{ key: "payment_method", label: "Payment method" }, { key: "bank_name", label: "Bank name" }, { key: "account_number", label: "Account number" }, { key: "account_type", label: "Account type" }],
};

export default function ProfileChangeRequestsPage() {
  const [type, setType] = useState("contact"); const [changes, setChanges] = useState<Record<string, string>>({}); const [note, setNote] = useState(""); const [evidence, setEvidence] = useState<File | null>(null); const [requests, setRequests] = useState<ChangeRequest[]>([]); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function authHeaders() { const { data: { session } } = await supabase.auth.getSession(); return session ? { Authorization: `Bearer ${session.access_token}` } : null; }
  async function load() { const headers = await authHeaders(); if (!headers) return setMessage("Your session has expired. Please sign in again."); const response = await fetch("/api/profile-change-requests", { headers }); const result = await response.json().catch(() => ({})); if (!response.ok) setMessage(result.error || "Requests could not be loaded."); else setRequests(result.requests || []); }
  useEffect(() => { void load(); }, []);
  async function submit() { const headers = await authHeaders(); if (!headers) return setMessage("Your session has expired. Please sign in again."); setSaving(true); setMessage(""); const body = new FormData(); body.set("requestType", type); body.set("changes", JSON.stringify(changes)); body.set("employeeNote", note); if (evidence) body.set("evidence", evidence); const response = await fetch("/api/profile-change-requests", { method: "POST", headers, body }); const result = await response.json().catch(() => ({})); if (!response.ok) setMessage(result.error || "Request could not be submitted."); else { setMessage("Request submitted for employer approval."); setChanges({}); setNote(""); setEvidence(null); await load(); } setSaving(false); }
  return <main style={page}><section style={header}><div><p style={eyebrow}>Employee self-service</p><h1 style={title}>Request a Profile Change</h1><p style={subtitle}>Your details remain unchanged until your employer approves this request. A bank letter or bank confirmation is required for every banking change.</p></div><Link href="/employee/profile" style={back}>Back to Profile</Link></section>{message && <p style={notice}>{message}</p>}<section style={card}><label style={label}>Change type<select style={input} value={type} onChange={(event) => { setType(event.target.value); setChanges({}); setEvidence(null); }}><option value="contact">Contact details</option><option value="emergency_contact">Emergency contact</option><option value="banking">Banking details</option></select></label><div style={grid}>{fields[type].map((field) => <label key={field.key} style={label}>{field.label}<input style={input} type={field.type || "text"} value={changes[field.key] || ""} onChange={(event) => setChanges((current) => ({ ...current, [field.key]: event.target.value }))} /></label>)}</div>{type === "banking" && <label style={label}>Bank letter / bank confirmation (PDF, JPG or PNG, max 10 MB)<input style={input} type="file" accept="application/pdf,image/jpeg,image/png" onChange={(event) => setEvidence(event.target.files?.[0] || null)} required /></label>}<label style={label}>Note for employer (optional)<textarea style={textarea} value={note} onChange={(event) => setNote(event.target.value)} /></label><button style={button} disabled={saving} onClick={submit}>{saving ? "Submitting…" : "Submit for approval"}</button></section><section style={card}><h2 style={heading}>My requests</h2>{requests.length === 0 ? <p style={muted}>No profile change requests yet.</p> : <div style={list}>{requests.map((request) => <article key={request.id} style={requestCard}><div><strong>{labels[request.request_type] || request.request_type}</strong><p style={muted}>{new Date(request.created_at).toLocaleDateString("en-ZA")}</p></div><span style={badge(request.status)}>{request.status}</span><p style={changesText}>{Object.entries(request.requested_changes || {}).filter(([, value]) => value).map(([key, value]) => `${key.replaceAll("_", " ")}: ${value}`).join(" · ")}</p>{request.employer_note && <p style={muted}>Employer note: {request.employer_note}</p>}</article>)}</div>}</section></main>;
}
const page={minHeight:"100vh",padding:38,background:"#f4f8fb",color:"#0f172a"}; const header={display:"flex",justifyContent:"space-between",gap:18,flexWrap:"wrap" as const,marginBottom:24}; const eyebrow={margin:"0 0 7px",color:"#b45309",fontWeight:900,fontSize:12,textTransform:"uppercase" as const}; const title={margin:0,color:"#0f766e",fontSize:34}; const subtitle={maxWidth:760,color:"#64748b",lineHeight:1.6}; const back={alignSelf:"start",padding:"10px 14px",border:"1px solid #0f766e",borderRadius:10,color:"#0f766e",textDecoration:"none",fontWeight:800}; const card={maxWidth:980,marginBottom:20,padding:22,border:"1px solid #e2e8f0",borderRadius:18,background:"#fff"}; const grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:14}; const label={display:"grid",gap:7,marginBottom:14,fontSize:13,fontWeight:800,color:"#334155"}; const input={width:"100%",boxSizing:"border-box" as const,padding:11,border:"1px solid #cbd5e1",borderRadius:9,fontSize:14,background:"#fff"}; const textarea={minHeight:86,padding:11,border:"1px solid #cbd5e1",borderRadius:9,fontSize:14}; const button={padding:"11px 16px",border:0,borderRadius:10,background:"#0f766e",color:"#fff",fontWeight:800,cursor:"pointer"}; const notice={maxWidth:980,padding:13,border:"1px solid #a5f3fc",borderRadius:10,background:"#ecfeff",color:"#155e75",fontWeight:700}; const heading={margin:"0 0 14px",fontSize:20}; const muted={margin:"4px 0",color:"#64748b",fontSize:13}; const list={display:"grid",gap:10}; const requestCard={padding:15,border:"1px solid #e2e8f0",borderRadius:12,background:"#f8fafc"}; const changesText={margin:"10px 0",fontSize:14,color:"#334155"}; const badge=(status:string)=>({display:"inline-block",marginTop:8,padding:"4px 8px",borderRadius:999,background:status==="Approved"?"#dcfce7":status==="Declined"?"#fee2e2":"#fef3c7",color:status==="Approved"?"#166534":status==="Declined"?"#991b1b":"#92400e",fontWeight:800,fontSize:12});
