"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { PasswordField } from "@/components/PasswordField";

export default function SecurityPage() {
  const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [message, setMessage] = useState(""); const [verifiedFactorId, setVerifiedFactorId] = useState(""); const [qrCode, setQrCode] = useState(""); const [factorId, setFactorId] = useState(""); const [code, setCode] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void loadFactors(); }, []);
  async function loadFactors() { const { data, error } = await supabase.auth.mfa.listFactors(); if (!error) setVerifiedFactorId(data.totp.find((factor) => factor.status === "verified")?.id || ""); }
  async function changePassword(event: React.FormEvent) { event.preventDefault(); if (!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,}$/.test(password)) return setMessage("Use at least 8 characters with uppercase, lowercase, a number and a special character."); if (password !== confirmPassword) return setMessage("Passwords do not match."); setSaving(true); const { error } = await supabase.auth.updateUser({ password }); setSaving(false); setMessage(error ? error.message : "Password updated successfully."); if (!error) { setPassword(""); setConfirmPassword(""); } }
  async function startMfa() { setMessage(""); const { data, error } = await supabase.auth.mfa.enroll({ factorType: "totp", friendlyName: "WageFlow authenticator", issuer: "WageFlow" }); if (error) return setMessage(error.message); setFactorId(data.id); setQrCode(`data:image/svg+xml;utf-8,${encodeURIComponent(data.totp.qr_code)}`); }
  async function verifyMfa() { if (!factorId || !code) return; setSaving(true); const { error } = await supabase.auth.mfa.challengeAndVerify({ factorId, code }); setSaving(false); if (error) return setMessage(error.message); setQrCode(""); setCode(""); setFactorId(""); setMessage("Two-factor authentication is now enabled."); await loadFactors(); }
  async function disableMfa() { if (!verifiedFactorId || !confirm("Disable two-factor authentication for this account?")) return; const { error } = await supabase.auth.mfa.unenroll({ factorId: verifiedFactorId }); setMessage(error ? error.message : "Two-factor authentication has been disabled."); if (!error) setVerifiedFactorId(""); }
  async function signOutOthers() { const { error } = await supabase.auth.signOut({ scope: "others" }); setMessage(error ? error.message : "Other signed-in sessions have been signed out."); }
  return <main style={page}><header style={header}><div><p style={eyebrow}>Account security</p><h1 style={title}>Security settings</h1><p style={subtitle}>Protect your WageFlow account with a strong password, two-factor authentication and session control.</p></div><Link href="/" style={back}>Home</Link></header>{message && <p style={notice}>{message}</p>}<section style={card}><h2 style={heading}>Password</h2><form onSubmit={changePassword} style={form}><PasswordField inputStyle={input} placeholder="New password" value={password} onChange={(event) => setPassword(event.target.value)} required /><PasswordField inputStyle={input} placeholder="Confirm new password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} required /><button style={button} disabled={saving}>Update password</button></form></section><section style={card}><h2 style={heading}>Two-factor authentication</h2>{verifiedFactorId ? <><p style={muted}>Two-factor authentication is enabled with your authenticator app.</p><button style={danger} onClick={() => void disableMfa()}>Disable two-factor authentication</button></> : qrCode ? <><p style={muted}>Scan this QR code in Google Authenticator, Microsoft Authenticator or another TOTP authenticator, then enter its six-digit code.</p><img src={qrCode} alt="Authenticator setup QR code" style={qr} /><div style={verifyRow}><input style={input} inputMode="numeric" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} placeholder="6-digit code" /><button style={button} disabled={saving} onClick={() => void verifyMfa()}>Verify and enable</button></div></> : <><p style={muted}>Add a second verification step when you sign in.</p><button style={button} onClick={() => void startMfa()}>Set up authenticator app</button></>}</section><section style={card}><h2 style={heading}>Active sessions</h2><p style={muted}>If you used a shared device or suspect an account issue, sign out of every other active session.</p><button style={outline} onClick={() => void signOutOthers()}>Sign out other sessions</button></section></main>;
}
const page = { minHeight: "100vh", padding: "28px clamp(16px,3vw,42px)", background: "#f4f8fb", color: "#0f172a" }; const header = { display: "flex", justifyContent: "space-between", gap: 16, flexWrap: "wrap" as const, marginBottom: 22 }; const eyebrow = { margin: 0, color: "#b7791f", fontSize: 12, fontWeight: 800, textTransform: "uppercase" as const }; const title = { margin: "5px 0", fontSize: "clamp(26px,3vw,30px)", color: "#0f766e" }; const subtitle = { margin: 0, color: "#64748b", maxWidth: 650, lineHeight: 1.55 }; const back = { padding: "10px 15px", border: "1px solid #0f766e", borderRadius: 10, color: "#0f766e", fontWeight: 800, textDecoration: "none" }; const card = { background: "#fff", border: "1px solid #e2e8f0", borderRadius: 16, padding: 20, marginBottom: 18, maxWidth: 680, boxShadow: "0 8px 24px rgba(15,23,42,.05)" }; const heading = { margin: "0 0 10px", fontSize: 19 }; const muted = { color: "#64748b", lineHeight: 1.55 }; const form = { display: "grid", gap: 12 }; const input = { boxSizing: "border-box" as const, width: "100%", padding: 11, border: "1px solid #cbd5e1", borderRadius: 10, font: "inherit" }; const button = { padding: "11px 16px", background: "#0f766e", color: "#fff", border: 0, borderRadius: 10, fontWeight: 800, cursor: "pointer" }; const outline = { ...button, color: "#0f766e", background: "#fff", border: "1px solid #0f766e" }; const danger = { ...button, color: "#b91c1c", background: "#fff", border: "1px solid #fecaca" }; const notice = { background: "#ecfeff", color: "#155e75", padding: 12, borderRadius: 10, fontWeight: 700, maxWidth: 680 }; const qr = { width: 190, height: 190, display: "block", margin: "14px 0" }; const verifyRow = { display: "flex", gap: 10, flexWrap: "wrap" as const, alignItems: "center" };
