"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../lib/supabaseClient";

type Schedule = { id: string; report_type: string; recipient_email: string; delivery_day: number; active: boolean; last_sent_at?: string | null };
const labels: Record<string, string> = { payroll_summary: "Payroll Summary", employee_master_list: "Employee Master List", employee_exit_report: "Employee Exit Report", uif_report: "UIF Report", paye_report: "PAYE Report" };

export default function ReportSchedulesPage() {
  const [items, setItems] = useState<Schedule[]>([]); const [reportType, setReportType] = useState("payroll_summary"); const [email, setEmail] = useState(""); const [day, setDay] = useState("1"); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void load(); }, []);
  async function request(url: string, init?: RequestInit) { const { data: { session } } = await supabase.auth.getSession(); const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}), Authorization: `Bearer ${session?.access_token || ""}` } }); return { response, body: await response.json().catch(() => ({})) }; }
  async function load() { const { response, body } = await request("/api/report-schedules"); if (!response.ok) setMessage(body.error || "Schedules could not be loaded."); else setItems(body.schedules || []); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); const { response, body } = await request("/api/report-schedules", { method: "POST", body: JSON.stringify({ reportType, email, day: Number(day) }) }); setSaving(false); if (!response.ok) return setMessage(body.error || "Schedule could not be saved."); setMessage("Scheduled report saved. It will be emailed on the selected day each month."); setEmail(""); await load(); }
  async function remove(id: string) { const { response, body } = await request(`/api/report-schedules?id=${encodeURIComponent(id)}`, { method: "DELETE" }); if (!response.ok) setMessage(body.error || "Schedule could not be removed."); else { setMessage("Scheduled report removed."); await load(); } }
  return <main style={page}><header style={header}><div><p style={eyebrow}>Automated delivery</p><h1 style={title}>Scheduled reports</h1><p style={subtitle}>Email a monthly report summary to a chosen recipient. The email links back to WageFlow for the full branded report export.</p></div><Link href="/employer/reports" style={back}>← Back to Reports</Link></header>{message && <p style={notice}>{message}</p>}<section style={card}><h2 style={heading}>Schedule a report</h2><form onSubmit={save} style={grid}><label style={field}><span style={label}>Report</span><select style={input} value={reportType} onChange={(event) => setReportType(event.target.value)}>{Object.entries(labels).map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label><label style={field}><span style={label}>Recipient email</span><input required type="email" style={input} value={email} onChange={(event) => setEmail(event.target.value)} placeholder="payroll@company.co.za" /></label><label style={field}><span style={label}>Delivery day</span><select style={input} value={day} onChange={(event) => setDay(event.target.value)}>{Array.from({ length: 28 }, (_, index) => <option key={index + 1} value={index + 1}>{index + 1}{suffix(index + 1)} of each month</option>)}</select></label><button style={button} disabled={saving}>{saving ? "Saving…" : "Save schedule"}</button></form></section><section style={card}><h2 style={heading}>Active schedules</h2>{items.length === 0 ? <p style={muted}>No reports are scheduled yet.</p> : <div style={list}>{items.map((item) => <article key={item.id} style={schedule}><div><strong>{labels[item.report_type] || item.report_type}</strong><p style={muted}>{item.recipient_email} · day {item.delivery_day} each month{item.last_sent_at ? ` · last sent ${new Date(item.last_sent_at).toLocaleDateString("en-ZA")}` : ""}</p></div><button style={removeButton} onClick={() => void remove(item.id)}>Remove</button></article>)}</div>}</section></main>;
}
function suffix(value: number) { return value % 10 === 1 && value !== 11 ? "st" : value % 10 === 2 && value !== 12 ? "nd" : value % 10 === 3 && value !== 13 ? "rd" : "th"; }
const page = { minHeight: "100vh", padding: "28px clamp(16px,3vw,42px)", background: "#f4f8fb", color: "#0f172a" }; const header = { display: "flex", justifyContent: "space-between", gap: 16, flexWrap: "wrap" as const, marginBottom: 22 }; const eyebrow = { margin: 0, color: "#b7791f", fontSize: 12, fontWeight: 800, textTransform: "uppercase" as const }; const title = { margin: "5px 0", fontSize: "clamp(26px,3vw,30px)", color: "#0f766e" }; const subtitle = { margin: 0, color: "#64748b", maxWidth: 680, lineHeight: 1.55 }; const back = { alignSelf: "flex-start", padding: "10px 15px", border: "1px solid #0f766e", borderRadius: 10, color: "#0f766e", fontWeight: 800, textDecoration: "none" }; const card = { background: "#fff", border: "1px solid #e2e8f0", borderRadius: 16, padding: 20, marginBottom: 18, boxShadow: "0 8px 24px rgba(15,23,42,.05)" }; const heading = { margin: "0 0 16px", fontSize: 19 }; const grid = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(210px,1fr))", gap: 14, alignItems: "end" }; const field = { display: "block" }; const label = { display: "block", color: "#475569", fontSize: 13, fontWeight: 800, marginBottom: 6 }; const input = { boxSizing: "border-box" as const, width: "100%", padding: 11, border: "1px solid #cbd5e1", borderRadius: 10, background: "#fff", font: "inherit" }; const button = { padding: "11px 16px", background: "#0f766e", color: "#fff", border: 0, borderRadius: 10, fontWeight: 800, cursor: "pointer" }; const notice = { background: "#ecfeff", color: "#155e75", padding: 12, borderRadius: 10, fontWeight: 700 }; const muted = { color: "#64748b", margin: "5px 0", lineHeight: 1.5 }; const list = { display: "grid", gap: 10 }; const schedule = { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 14, flexWrap: "wrap" as const, padding: 14, border: "1px solid #e2e8f0", borderRadius: 12 }; const removeButton = { padding: "8px 11px", color: "#b91c1c", background: "#fff", border: "1px solid #fecaca", borderRadius: 9, fontWeight: 800, cursor: "pointer" };
